spring:
  datasource:
      url: jdbc:h2:mem:test_db
      driver-class-name: org.h2.Driver
      username: user
      password:
  h2:
    console:
      enabled: true
      path: /db
  jpa:
    hibernate:
      ddl-auto: create